server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: druid-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://xxxx:3306/wqh?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: xxxx
      password: xxxx
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 链接池配置
      # 配置初始化大小、最小、最大
      initial-size: 100
      max-active: 102
      min-idle: 101
      # 获取链接等待超时时间
      max-wait: 60000
      pool-prepared-statements: true
      #
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 间隔多久进行一次检测，检测须要关闭的空闲链接
      time-between-eviction-runs-millis: 60000
      # 一个链接在链接池中最小的生存时间
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      filters: stat
      filter:
        # 慢SQL记录(sql语句执行时间超过某个界限就记录下来)
        stat:
          slow-sql-millis: 200
          log-slow-sql: true

      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 登陆监控界面的用户名以及密码，登陆url为localhost:8080/druid
        login-username: admin
        login-password: admin
        allow:
        deny:
