server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:3306/my_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: xxxxxx
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true